### ISSUE TITLE
5.0.5 无法运行

### ISSUE THREAD

**Issue by iwpz** [TencentCloud/tc-chat-sdk-flutter#2]
```
Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Consecutive statements on a line must be separated by ';'
/Users/{me}/.pub-cache/hosted/pub.flutter-io.cn/tencent_im_sdk_plugin-5.0.5/ios/Classes/manager/MessageManager.swift:1232:21
```

问题应该是
https://github.com/TencentCloud/chat-sdk-flutter/blob/f368d546bd9e57ec419e13e9bfddcc2f13444ad5/tencent_im_sdk_plugin/ios/Classes/manager/MessageManager.swift#L1233
这里的else if写成了if。
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/16379552/217707895-628910b4-71fa-491e-a216-1657cfe53559.png">
烦请官方抽空更新一下，谢谢。

**Comment by helberappservice** [comment]
我也发现了，自己改了下，就好了~

**Comment by hexingcheng** [comment]
https://pub.dev/packages/tencent_cloud_chat_sdk/versions 可以在这里下载最新的SDK，并且做二次开发
