### ISSUE TITLE
版本5.1.3 ios TXIMSDK_Plus_iOS版本冲突

### ISSUE THREAD

**Issue by qflbai** [TencentCloud/tc-chat-sdk-flutter#3]
<img width="824" alt="WeChat97700ecdce90289b1cb5624ec1fc106b" src="https://user-images.githubusercontent.com/23705172/228113593-910553ec-d400-4ae7-b5d4-a8ee82d70f9d.png">
如图：TXIMSDK_Plus_iOS 版本冲突。

**Comment by shitaBro** [comment]
same question

**Comment by hexingcheng** [comment]
同时集成了tencent_im_sdk_plugin和tencent_cloud_chat_sdk吧，这两个本来就是同一个SDK，tencent_cloud_chat_sdk是改名后的版本，这样集成肯定会冲突的。去掉tencent_im_sdk_plugin这个依赖即可。

**Comment by shitaBro** [comment]
集成推送的时候，只保留 `tencent_chat_push_for_china: ^2.6.0`
