### ISSUE TITLE
CocoaPods could not find compatible versions for pod "TXIMSDK_Plus_iOS"

### ISSUE THREAD

**Issue by shitaBro** [TencentCloud/tc-chat-sdk-flutter#4]
CocoaPods could not find compatible versions for pod "TXIMSDK_Plus_iOS":
In snapshot (Podfile.lock):
TXIMSDK_Plus_iOS (= 6.6.3002)

In Podfile:
tencent_cloud_chat_sdk (from .symlinks/plugins/tencent_cloud_chat_sdk/ios) was resolved to 5.1.2, which depends on
TXIMSDK_Plus_iOS (= 7.1.3925)

tencent_im_sdk_plugin (from `.symlinks/plugins/tencent_im_sdk_plugin/ios`) was resolved to 5.0.4, which depends on
  TXIMSDK_Plus_iOS (= 6.9.3557)
Specs satisfying the TXIMSDK_Plus_iOS (= 6.6.3002), TXIMSDK_Plus_iOS (= 7.1.3925), TXIMSDK_Plus_iOS (= 6.9.3557) dependency were found, but they required a higher minimum deployment target.

flutter yaml
tencent_chat_push_for_china: ^2.6.0
tencent_im_sdk_plugin: ^5.0.5

**Comment by hexingcheng** [comment]
这个问题可以删掉lock后重新更新install ios依赖即可
