### ISSUE TITLE
Flutter 3.7 下5.0.3 5.0.4 5.0.5都编译有问题，导致Flutter无法生成info.plist

### ISSUE THREAD

**Issue by xmdcy2011** [TencentCloud/tc-chat-sdk-flutter#5]
![image](https://user-images.githubusercontent.com/16028807/233912383-da25f5c7-c2d7-4d05-92b0-d3d544c4de24.png)

**Comment by xmdcy2011** [comment]
我暂时只能使用4.2.0

**Comment by hexingcheng** [comment]
https://pub.dev/packages/tencent_cloud_chat_sdk/versions 可以在这里下载最新的SDK，并且做二次开发
